[package]
name = "ch-rs"
version = "0.1.0"
edition = "2021"
readme = "README.md"
build = "build.rs"

[profile.release]
lto = true
opt-level = 'z'

[dependencies]
slint = "1.1.0"
log = "0.4.20"
log4rs = "1.2.0"

[build-dependencies]
slint-build = "1.1.0"