import { SideBar } from "side_bar.slint";
import { Home } from "home.slint";
import { Setting } from "setting.slint";
import { About } from "about.slint";

export component AppWindow inherits Window {
    preferred-width: 1024px;
    preferred-height: 768px;
    title: @tr("ch-rs");
    icon: @image-url("./images/logo/logo.png");

    HorizontalLayout {
        side-bar := SideBar {
            title: @tr("ch-rs");
            model: [
                @tr("Menu" => "首页"), 
                @tr("Menu" => "执行脚本"), 
                @tr("Menu" => "执行脚本"), 
                @tr("Menu" => "设置"), 
                @tr("Menu" => "关于")
            ];
        }

        if(side-bar.current-item == 0) : Home {}
        if(side-bar.current-item == 1) : Home {}
        if(side-bar.current-item == 2) : Home {}
        if(side-bar.current-item == 3) : Setting {}
        if(side-bar.current-item == 4) : About {}
    }
}